
####################
# Certbot defaults #
####################

COMPUTATE_CERTBOT_DOMAIN_NAME: "..."

# The OpenShift base URL where applications will be deployed. 
REDHAT_OPENSHIFT_HOST: "..."
# The OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request). 
REDHAT_OPENSHIFT_TOKEN: "..."
# The OpenShift namespace where applications will be deployed. 
REDHAT_OPENSHIFT_NAMESPACE: school
# The Default OpenShift storage class to use for persistent volume claims. 
REDHAT_OPENSHIFT_STORAGE_CLASS_NAME: gp2

#######################
# PostgreSQL defaults #
#######################

# The default port that PostgreSQL runs. 
POSTGRES_PORT: 5432
# The PostgreSQL OpenShift base URL where PostgreSQL will be deployed. 
POSTGRES_HOST: "{{REDHAT_OPENSHIFT_HOST}}"
# The PostgreSQL OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request). 
POSTGRES_TOKEN: "{{REDHAT_OPENSHIFT_TOKEN}}"
# The PostgreSQL OpenShift namespace where PostgreSQL be deployed. 
POSTGRES_NAMESPACE: "{{REDHAT_OPENSHIFT_NAMESPACE}}"
# The PostgreSQL volume size for Solr files. 
POSTGRES_VOLUME_SIZE: 2Gi
# The default hostname for the PostreSQL database. 
POSTGRES_HOST_NAME: "postgres.{{POSTGRES_NAMESPACE}}.svc"
# The default username for the PostreSQL database. 
POSTGRES_DB_USER: computate
# The default PostgreSQL database name. 
POSTGRES_DB_NAME: southerncoalition
# The default PostgreSQL database password. 
POSTGRES_DB_PASSWORD: "..."
# The max database connection pool size of each verticle instance. 
# Keep in mind that each verticle instance defined in REDHAT_ANSIBLE_TOWER_SITE_INSTANCES plus 1 worker verticle will each have this number of connections. 
# The default max connections for PostgreSQL is 100. 
REDHAT_ANSIBLE_TOWER_JDBC_MAX_POOL_SIZE: 8

#################################
# ansible tower global defaults #
#################################

# The ansible tower OpenShift base URL where ansible tower will be deployed. 
REDHAT_ANSIBLE_TOWER_HOST: "{{ REDHAT_OPENSHIFT_HOST }}"
# The ansible tower OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request). 
REDHAT_ANSIBLE_TOWER_TOKEN: "{{ REDHAT_OPENSHIFT_TOKEN }}"
# The ansible tower OpenShift namespace where ansible tower be deployed. 
REDHAT_ANSIBLE_TOWER_NAMESPACE: "{{ REDHAT_OPENSHIFT_NAMESPACE }}"

#####################################
# ansible tower US English defaults #
#####################################

# The Ansible Tower version
REDHAT_ANSIBLE_TOWER_VERSION: 3.7.0
# The Ansible Tower persistent volume claim name. 
REDHAT_ANSIBLE_TOWER_VOLUME_NAME: postgresql
# The Ansible Tower volume size for Solr files. 
REDHAT_ANSIBLE_TOWER_VOLUME_SIZE: 1Gi
# The Ansible Tower admin password of the site. 
REDHAT_ANSIBLE_TOWER_ADMIN_PASSWORD: "..."
# The Ansible Tower secret key. 
# It's *very* important that this stay the same between upgrades or you will lose
# the ability to decrypt your credentials. 
REDHAT_ANSIBLE_TOWER_SECRET_KEY: "..."
# The PostgreSQL database host name of the site. 
REDHAT_ANSIBLE_TOWER_DB_HOST_NAME: "postgresql"
# The PostgreSQL database user name of the site. 
REDHAT_ANSIBLE_TOWER_DB_USER: tower
# The PostgreSQL database password of the site. 
REDHAT_ANSIBLE_TOWER_DB_PASSWORD: "..."
# The PostgreSQL database name of the site. 
REDHAT_ANSIBLE_TOWER_DB_NAME: tower


# The domain name of the site. 
REDHAT_ANSIBLE_TOWER_DOMAIN_NAME: "{{ COMPUTATE_CERTBOT_DOMAIN_NAME }}"
# The host name of the site. 
REDHAT_ANSIBLE_TOWER_SITE_HOST_NAME: "www.{{ REDHAT_ANSIBLE_TOWER_DOMAIN_NAME }}"
# The port of the site. 
REDHAT_ANSIBLE_TOWER_SITE_PORT: "8080"
# The base URL of the site. 
REDHAT_ANSIBLE_TOWER_SITE_BASE_URL_ENUS: "https://{{ REDHAT_ANSIBLE_TOWER_SITE_HOST_NAME }}"
# The Solr collection of the site. 
REDHAT_ANSIBLE_TOWER_SOLR_COLLECTION: "school"
# The timezone of the site. 
REDHAT_ANSIBLE_TOWER_SITE_ZONE_ENUS: "America/Denver"
# The Java main class of the site. 
REDHAT_ANSIBLE_TOWER_JAVA_MAIN_CLASS_ENUS: org.computate.scolaire.enUS.vertx.AppVertx
JAVA_MAIN_CLASS: org.computate.scolaire.enUS.vertx.AppVertx
# The backup directory of the site. 
REDHAT_ANSIBLE_TOWER_BACKUP_DIR_ENUS: "{{ REPO_PATH }}/data"
# The restore directory of the site. 
REDHAT_ANSIBLE_TOWER_RESTORE_DIR_ENUS: "{{ REPO_PATH }}/Friday"
# The number of Vert.X Verticle instances to deploy. 
REDHAT_ANSIBLE_TOWER_SITE_INSTANCES: 6

# The password for encrypting and decrypting backup data. 
VAULT_PASSWORD: "..."

#################
# SMTP defaults #
#################

# The email SMTP host name. 
EMAIL_HOST_NAME: smtp.example.com
# The email SMTP port. 
EMAIL_PORT: 465
# The email SMTP from email address. 
EMAIL_FROM: "..."
# The admin email addresses that will receive error messages from the application. 
EMAIL_ADMIN: "{{ EMAIL_FROM }}"
# Whether email SMTP SSL/TLS encryption is enabled. 
EMAIL_SSL: true
# Whether email SMTP username password authentication is enabled. 
EMAIL_AUTH: true
# The email SMTP username. 
EMAIL_USER: "..."
EMAIL_PASSWORD: "..."

####################
# SSL/TLS defaults #
####################

# The keystore alias. 
SSL_ALIAS: "{{REDHAT_ANSIBLE_TOWER_DOMAIN_NAME_FRFR}}"
# The keystore directory. 
SSL_KEYSTORE_PATH: /opt/keystore
# The properties file where the SSL/TLS encryption is configured. 
SSL_PROPERTIES_FILENAME: ansible tower-keystore.properties
# The keystore filename. 
SSL_JKS_FILENAME: "{{SSL_ALIAS}}.jks"
# The keystore path. 
SSL_JKS_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_JKS_FILENAME}}"
# The certificate filename. 
SSL_CRT_FILENAME: "{{SSL_ALIAS}}.crt"
# The certificate path. 
SSL_CRT_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_CRT_FILENAME}}"
# The private key filename. 
SSL_KEY_FILENAME: "{{SSL_ALIAS}}.key"
# The private key path. 
SSL_KEY_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_KEY_FILENAME}}"
# The p12 file password. 
SSL_P12_PASSWORD: "..."
# The keystore file password. 
SSL_JKS_PASSWORD: "{{SSL_P12_PASSWORD}}"
# The keystore file base64 encoded (base64 -w 0 /opt/keystore/computate.org.jks). 
SSL_JKS_BASE64: "..."
# The jceks file base64 encoded (base64 -w 0 /opt/keystore/computate.org.jceks). 
SSL_JCEKS_BASE64: "..."

#######################################
# OpenID Connect auth server defaults #
#######################################

# The Red Hat SSO OpenShift base URL where Red Hat SSO will be deployed. 
SSO_HOST: "{{REDHAT_OPENSHIFT_HOST}}"
# The Red Hat SSO OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request). 
SSO_TOKEN: "{{REDHAT_OPENSHIFT_TOKEN}}"
# The Red Hat SSO OpenShift namespace where Red Hat SSO be deployed. 
SSO_NAMESPACE: "{{REDHAT_OPENSHIFT_NAMESPACE}}"
# The default username for the Red Hat SSO PostreSQL database. 
SSO_DB_USERNAME: "..."
# The default Red Hat SSO PostgreSQL database password. 
SSO_DB_PASSWORD: "..."
# The default Red Hat SSO PostgreSQL database name. 
SSO_DB_DATABASE: root
# The Red Hat SSO HTTPS keystore alias. 
SSO_HTTPS_NAME: "{{SSL_ALIAS}}"
# The Red Hat SSO HTTPS keystore file password. 
SSO_HTTPS_PASSWORD: "{{SSL_JKS_PASSWORD}}"
# The Red Hat SSO JGroups keystore alias. 
SSO_JGROUPS_ENCRYPT_NAME: "{{SSL_ALIAS}}"
# The Red Hat SSO JGroups keystore file password. 
SSO_JGROUPS_ENCRYPT_PASSWORD: "{{SSL_JKS_PASSWORD}}"
# A Red Hat SSO JGroups cluster password. 
SSO_JGROUPS_CLUSTER_PASSWORD: "..."
# A Red Hat SSO admin username. 
SSO_ADMIN_USERNAME: "..."
# A Red Hat SSO admin password. 
SSO_ADMIN_PASSWORD: "..."
SSO_REALM: "{{AUTH_REALM}}"
# A Red Hat SSO initial user username. 
SSO_SERVICE_USERNAME: "..."
# A Red Hat SSO initial user password. 
SSO_SERVICE_PASSWORD: "..."
# The Red Hat SSO truststore file password. 
SSO_TRUSTSTORE_PASSWORD: "{{SSL_JKS_PASSWORD}}"
# The Red Hat SSO volume size for Solr files. 
SSO_VOLUME_SIZE: 1Gi
# The default hostname for Red Hat SSO. 
SSO_SITE_HOST_NAME: "sso.example.com"

# The Auth realm. 
AUTH_REALM: EXAMPLE.COM
# The Auth client or resource. 
AUTH_RESOURCE: example.com
# The Auth secret. 
AUTH_SECRET: "..."
# The Auth URL. 
AUTH_URL: https://sso.example.com/auth
