
######################################
# computate-medicale system defaults #
######################################

# The name of this application. 
COMPUTATE_MEDICALE_NAME: computate-medicale
# The default source code directory for the computate application which helps generate and translate most the code. 
COMPUTATE_SRC: "/usr/local/src/computate"
# The default source code directory for the computate-medicale project. 
COMPUTATE_MEDICALE_SRC: "/usr/local/src/{{COMPUTATE_MEDICALE_NAME}}"
# The default language of the computate-medicale project code which is French in France. 
COMPUTATE_MEDICALE_LANG: "frFR"
# The default config file for the computate-medicale project. 
COMPUTATE_MEDICALE_CONFIG: "{{COMPUTATE_MEDICALE_SRC}}/config/{{COMPUTATE_MEDICALE_NAME}}.config"
# The US English config file for the computate-medicale project. 
COMPUTATE_MEDICALE_CONFIG_enUS: "{{COMPUTATE_MEDICALE_SRC}}/config/{{COMPUTATE_MEDICALE_NAME}}-enUS.config"
# The systemd service name for computate-medicale that generates and translates most of the code. 
COMPUTATE_MEDICALE_SERVICE: "regarder-{{COMPUTATE_MEDICALE_NAME}}"
# The systemd service file for computate-medicale that generates and translates most of the code. 
COMPUTATE_MEDICALE_SYSTEMD: "/usr/lib/systemd/system/{{COMPUTATE_MEDICALE_SERVICE}}.service"
# The main git repository for the computate-medicale project. 
COMPUTATE_MEDICALE_REPO: "https://github.com/computate/{{COMPUTATE_MEDICALE_NAME}}.git"
# The target ansible inventory group for the computate-medicale project to setup your own hosts under this name to deploy the application to. 
target: computate_medicale

####################
# Ansible defaults #
####################

# Add to an ansible-vault the username of your user on your computer (echo $HOSTNAME). 
USER_NAME: "..."
# Add to an ansible-vault the password of your user on your computer to become root for configuring the applications. 
USER_PASSWORD: "..."
# Setup the ansible user when running the playbook as your user. 
ansible_user: "{{USER_NAME}}"
# Setup the ansible sudo password as your password when running the playbook. 
ansible_sudo_pass: "{{USER_PASSWORD}}"
# Setup the ansible password for elevated privileges as your password when running the playbook. 
ansible_become_pass: "{{USER_PASSWORD}}"
# Setup the ansible password for ssh as your password when running the playbook. 
ansible_ssh_pass: "{{USER_PASSWORD}}"
# Setup the decryption password for decrypting other secrets in the playbook. 
VAULT_PASSWORD: "{{USER_PASSWORD}}"

######################
# Zookeeper defaults #
######################

# The default hostname for the Zookeeper cluster manager. 
ZOOKEEPER_HOSTNAME: "localhost"
# The default port that Zookeeper runs to manage the cluster. 
ZOOKEEPER_PORT: 2181

#################
# Solr defaults #
#################

# The installation directory of Solr. 
SOLR_OPT: /opt/solr
# The default hostname for the Solr search engine. 
SOLR_HOST_NAME: localhost
# The default port that Solr runs. 
SOLR_PORT: 8983

#######################
# PostgreSQL defaults #
#######################

# The default hostname for the PostreSQL database. 
POSTGRES_HOST_NAME: "localhost"
# The default username that the PostgreSQL server runs with. 
POSTGRES_BECOME_USER: "postgres"
# The default path to the PostgreSQL hba file to manage user permissions. 
POSTGRES_HBA_CONF: "/var/lib/pgsql/data/pg_hba.conf"
# The default PostgreSQL service name. 
POSTGRES_SERVICE: "postgresql"

#####################################
# computate-medical global defaults #
#####################################

# The base URL where the static files will point to.  
COMPUTATE_MEDICALE_STATIC_BASE_URL: "https://example.neocities.org"
# The number of background worker executors that may run. 
COMPUTATE_MEDICALE_NUMBER_EXECUTORS: 5
# The properties file where the SSL/TLS encryption is configured. 
COMPUTATE_MEDICALE_SSL_PROPERTIES_FILENAME: computate-medicale-keystore.properties

################################################
# computate-medicale French in France defaults #
################################################

# The domain name of the site. 
COMPUTATE_MEDICALE_DOMAIN_NAME_FRFR: "example.com"
# The host name of the site. 
COMPUTATE_MEDICALE_SITE_HOST_NAME_FRFR: "medicale-dev.{{COMPUTATE_MEDICALE_DOMAIN_NAME_FRFR}}"
# The port of the site. 
COMPUTATE_MEDICALE_SITE_PORT_FRFR: "10580"
# The base URL of the site. 
COMPUTATE_MEDICALE_SITE_BASE_URL_FRFR: "https://{{COMPUTATE_MEDICALE_SITE_HOST_NAME_FRFR}}:{{COMPUTATE_MEDICALE_SITE_PORT_FRFR}}"
# The Solr collection of the site. 
COMPUTATE_MEDICALE_SOLR_COLLECTION_FRFR: "medicale"
# The timezone of the site. 
COMPUTATE_MEDICALE_SITE_ZONE_FRFR: "France/Paris"
# The PostgreSQL database host name of the site. 
COMPUTATE_MEDICALE_DB_HOST_NAME_FRFR: "localhost"
# The PostgreSQL database user name of the site. 
COMPUTATE_MEDICALE_DB_USER_FRFR: computate
# The PostgreSQL database password of the site. 
COMPUTATE_MEDICALE_DB_PASSWORD_FRFR: "..."
# The PostgreSQL database name of the site. 
COMPUTATE_MEDICALE_DB_NAME_FRFR: medicale
# The Java main class of the site. 
COMPUTATE_MEDICALE_JAVA_MAIN_CLASS_FRFR: org.computate.medicale.frFR.vertx.AppliVertx
# The backup directory of the site. 
COMPUTATE_MEDICALE_BACKUP_DIR_FRFR: /usr/local/src/computate-medicale-static/data/frFR
# The restore directory of the site. 
COMPUTATE_MEDICALE_RESTORE_DIR_FRFR: /home/ctate/backup/medicale-dev/frFR

#################################################
# computate-medicale English in the US defaults #
#################################################

# The domain name of the site. 
COMPUTATE_MEDICALE_DOMAIN_NAME_ENUS: "example.com"
# The host name of the site. 
COMPUTATE_MEDICALE_SITE_HOST_NAME_ENUS: "medicale-dev.{{COMPUTATE_MEDICALE_DOMAIN_NAME_ENUS}}"
# The port of the site. 
COMPUTATE_MEDICALE_SITE_PORT_ENUS: "10581"
# The base URL of the site. 
COMPUTATE_MEDICALE_SITE_BASE_URL_ENUS: "https://{{COMPUTATE_MEDICALE_SITE_HOST_NAME_ENUS}}:{{COMPUTATE_MEDICALE_SITE_PORT_ENUS}}"
# The Solr collection of the site. 
COMPUTATE_MEDICALE_SOLR_COLLECTION_ENUS: "medical"
# The timezone of the site. 
COMPUTATE_MEDICALE_SITE_ZONE_ENUS: "America/Denver"
# The PostgreSQL database host name of the site. 
COMPUTATE_MEDICALE_DB_HOST_NAME_ENUS: "localhost"
# The PostgreSQL database user name of the site. 
COMPUTATE_MEDICALE_DB_USER_ENUS: computate
# The PostgreSQL database password of the site. 
COMPUTATE_MEDICALE_DB_PASSWORD_ENUS: "..."
# The PostgreSQL database name of the site. 
COMPUTATE_MEDICALE_DB_NAME_ENUS: medical
# The Java main class of the site. 
COMPUTATE_MEDICALE_JAVA_MAIN_CLASS_ENUS: org.computate.medicale.enUS.vertx.AppVertx
# The backup directory of the site. 
COMPUTATE_MEDICALE_BACKUP_DIR_ENUS: /usr/local/src/computate-medicale-static/data/enUS
# The restore directory of the site. 
COMPUTATE_MEDICALE_RESTORE_DIR_ENUS: /home/ctate/backup/medicale-dev/enUS

#################
# SMTP defaults #
#################

# The email SMTP host name. 
EMAIL_HOST_NAME: smtp.example.com
# The email SMTP port. 
EMAIL_PORT: 465
# The email SMTP from email address. 
EMAIL_FROM: "..."
# Whether email SMTP SSL/TLS encryption is enabled. 
EMAIL_SSL: true
# Whether email SMTP username password authentication is enabled. 
EMAIL_AUTH: true
# The email SMTP username. 
EMAIL_USER: "..."
EMAIL_PASSWORD: "..."

#######################################
# OpenID Connect auth server defaults #
#######################################

# The Single Sign On host name. 
SSO_SITE_HOST_NAME: "sso.example.com"
# The Auth realm. 
AUTH_REALM: EXAMPLE.COM
# The Auth client or resource. 
AUTH_RESOURCE: example.com
# The Auth secret. 
AUTH_SECRET: "..."
# The Auth URL. 
AUTH_URL: https://sso.example.com/auth

####################
# SSL/TLS defaults #
####################

# The keystore alias. 
SSL_ALIAS: "{{COMPUTATE_MEDICALE_DOMAIN_NAME_FRFR}}"
# The keystore directory. 
SSL_KEYSTORE_PATH: /opt/keystore
# The keystore properties filename. 
SSL_PROPERTIES_FILENAME: "{{COMPUTATE_MEDICALE_SSL_PROPERTIES_FILENAME}}"
# The keystore filename. 
SSL_JKS_FILENAME: "{{SSL_ALIAS}}.jks"
# The keystore path. 
SSL_JKS_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_JKS_FILENAME}}"
# The certificate filename. 
SSL_CRT_FILENAME: "{{SSL_ALIAS}}.crt"
# The certificate path. 
SSL_CRT_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_CRT_FILENAME}}"
# The private key filename. 
SSL_KEY_FILENAME: "{{SSL_ALIAS}}.key"
# The private key path. 
SSL_KEY_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_KEY_FILENAME}}"
# The p12 file password. 
SSL_P12_PASSWORD: "..."
# The keystore file password. 
SSL_JKS_PASSWORD: "{{SSL_P12_PASSWORD}}"
# The keystore file base64 encoded (base64 -w 0 /opt/keystore/computate.org.jks). 
SSL_JKS_BASE64: "..."
# The jceks file base64 encoded (base64 -w 0 /opt/keystore/computate.org.jceks). 
SSL_JCEKS_BASE64: "..."
