---
- name: Get restore site access token
  shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
  register: AUTH_TOKEN

