---
- name: Sign in to the application through the SSO server
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_login }
- name: Backup the southerncoalition page-design data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup, DATA_NAME_VAR: page-design, DATA_URI: /api/admin/page-design, DATA_ROWS: 500 }
- name: Backup the southerncoalition html-part data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part, DATA_ROWS: 500 }
