SILK_NAME: silk
SILK_SRC: "/usr/local/src/{{SILK_NAME}}"
SILK_OPT: "/opt/{{SILK_NAME}}"
SILK_SYSTEMD: "/usr/lib/systemd/system/{{SILK_NAME}}.service"
SILK_SERVICE: "{{SILK_NAME}}"
SILK_REPO: "https://github.com/lucidworks/silk.git"
SILK_VERSION: dev
SILK_TAG: "dev"
SILK_PORT: 5601
SILK_CONFIGSET: silkconfig
SILK_COLLECTION: silkconfig
SOLR_OPT: "/opt/solr"
ZOOKEEPER_HOSTNAME: localhost
ZOOKEEPER_CLIENT_PORT: 2181
target: computate_silk

